# Generated by Django 5.1.6 on 2025-02-14 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slup',
            new_name='slug',
        ),
    ]
