# Generated by Django 5.1.6 on 2025-02-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_body_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
