# Generated by Django 5.1.6 on 2025-04-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
