# Generated by Django 5.1.6 on 2025-08-08 12:52

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_post_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[1920, 1080], upload_to='', verbose_name=[600, 600]),
        ),
    ]
