# Generated by Django 5.1.6 on 2025-08-09 12:32

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=(600, 600), upload_to=''),
        ),
    ]
