# Generated by Django 5.1.6 on 2025-05-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_alter_coffee_acidity_alter_coffee_roast_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CuppingNotes',
            new_name='CuppingNote',
        ),
    ]
