# Generated by Django 5.1.6 on 2025-07-11 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_critic_score_coffee_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='score',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='scores',
        ),
        migrations.AddField(
            model_name='score',
            name='coffee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee.coffee'),
        ),
    ]
