# Generated by Django 5.1.6 on 2025-07-11 20:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_remove_coffee_score_remove_coffee_scores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
