# Generated by Django 5.1.6 on 2025-07-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_score_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='coffee',
        ),
        migrations.RemoveField(
            model_name='score',
            name='created_on',
        ),
    ]
