# Generated by Django 5.1.6 on 2025-07-11 20:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_remove_score_coffee_remove_score_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='coffee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coffee.coffee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
