# Generated by Django 5.1.6 on 2025-07-15 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_score_coffee_score_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='author',
            new_name='critic',
        ),
    ]
