# Generated by Django 5.1.6 on 2025-08-07 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_rename_author_score_critic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
