# Generated by Django 5.1.6 on 2025-08-07 00:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0010_alter_coffee_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
