# Generated by Django 5.1.6 on 2025-08-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0011_alter_score_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
