# Generated by Django 5.1.6 on 2025-08-31 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0013_processing_coffee_processing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='cuppingnote',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='roaster',
            options={'ordering': ['name']},
        ),
    ]
