# Generated by Django 5.1.6 on 2025-09-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0014_alter_country_options_alter_cuppingnote_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffee',
            options={'ordering': ['-created_on']},
        ),
    ]
