# Generated by Django 5.1.6 on 2025-12-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0015_alter_coffee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='processing_new',
            field=models.ManyToManyField(blank=True, related_name='coffees', to='coffee.processing'),
        ),
    ]
