# Generated by Django 5.1.6 on 2025-12-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0016_coffee_processing_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='processing',
        ),
    ]
