# Generated by Django 5.1.6 on 2025-12-09 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0017_remove_coffee_processing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='processing_new',
            new_name='processing',
        ),
    ]
