# Generated by Django 5.1.6 on 2025-12-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0018_rename_processing_new_coffee_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
