# Generated by Django 5.1.6 on 2025-12-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0019_coffee_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
