# Generated by Django 5.1.6 on 2025-12-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0020_alter_coffee_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
