# Generated by Django 5.1.6 on 2026-05-21 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0020_alter_coffee_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Score',
            new_name='Review',
        ),
    ]
