# Generated by Django 5.1.6 on 2026-06-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0021_rename_score_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
