# Generated by Django 5.1.6 on 2026-07-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0022_review_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varietal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='coffee',
            name='varietal',
            field=models.ManyToManyField(blank=True, related_name='coffees', to='coffee.varietal'),
        ),
    ]
