# Generated by Django 5.1.6 on 2026-10-07 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0023_varietal_coffee_varietal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varietal',
            options={'ordering': ['name']},
        ),
    ]
